#!/bin/sh

export scriptdir=`pwd`


export METEO_DIR=${scriptdir}/meteo
export OUTPUT_DIR=${scriptdir}/output
export BOUNDARY_DIR=${scriptdir}/SILAM-bnd


#export silam_binary=${scriptdir}/silam-model/bin/silam_v5_6.gnumpi # MPI run
export silam_binary=${scriptdir}/../silam-model/bin/silam_v5_8pub.gnu   # serial run
export silam_ini=${scriptdir}/../silam-model/ini  

#export OMP_NUM_THREADS=8


export outsuff="" ## Can be set non-empty to alter the  output directory

export fcdate=`date -u -d "3 hours" +%Y%m%d`

export maxhours=48

export email="test-kaz"
export lonrange="44.,90."
export latrange="35.,61."
export suitename="KAZ"

export publish=true
# Geometry depends on the picture Upper-leftcorner of logo with respect
# to upper-left corner of a picture 
export PUTLOGOCMD="composite  -geometry  +110+475  $scriptdir/fmi-logo-60x30a.png"
# Special logo for aqi and pollen index pictures
export PUTLOGOCMDINDEX="$PUTLOGOCMD"
